const cards = [
  {
    "Identifiant": 1,
    "Nom": "Relance jusqu’à 2 dés",
    "Étiquettes": "Gestion de dés",
    "Bonus mouvement parfait": "",
    "Prise": "Jug",
    "Profil": "Vertical",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 9,
    "Nom": "Vole un dé à un autre joueur",
    "Étiquettes": "#pute, Gestion de dés, Interaction",
    "Bonus mouvement parfait": "",
    "Prise": "Jug",
    "Profil": "Toit",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 2,
    "Nom": "Ajoute +2 au total",
    "Étiquettes": "Gestion de dés",
    "Bonus mouvement parfait": "",
    "Prise": "Pocket",
    "Profil": "Vertical",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 23,
    "Nom": "Relance 1 dé",
    "Étiquettes": "Gestion de dés",
    "Bonus mouvement parfait": "",
    "Prise": "Pocket",
    "Profil": "Toit",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 3,
    "Nom": "Garde tous tes dés en cas de réussite",
    "Étiquettes": "Gestion de dés",
    "Bonus mouvement parfait": "",
    "Prise": "Crimp",
    "Profil": "Vertical",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 29,
    "Nom": "Tu peux relancer tous tes dés",
    "Étiquettes": "Gestion de dés",
    "Bonus mouvement parfait": "",
    "Prise": "Crimp",
    "Profil": "Toit",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 4,
    "Nom": "Garde tous tes dés en cas d’échec",
    "Étiquettes": "Gestion de dés",
    "Bonus mouvement parfait": "",
    "Prise": "Slopper",
    "Profil": "Vertical",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 30,
    "Nom": "Plus ou moins 1 au résultat d’un dé",
    "Étiquettes": "Gestion de dés",
    "Bonus mouvement parfait": "",
    "Prise": "Slopper",
    "Profil": "Toit",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 5,
    "Nom": "Echange ton pool de dés avec un autre joueur",
    "Étiquettes": "#pute, Gestion de dés, Interaction",
    "Bonus mouvement parfait": "",
    "Prise": "Horn",
    "Profil": "Vertical",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 31,
    "Nom": "Garde tous tes dés joués ce tour",
    "Étiquettes": "Gestion de dés",
    "Bonus mouvement parfait": "",
    "Prise": "Horn",
    "Profil": "Toit",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 6,
    "Nom": "Récupère un dé immédiatement",
    "Étiquettes": "Gestion de dés",
    "Bonus mouvement parfait": "",
    "Prise": "Pinch",
    "Profil": "Vertical",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 32,
    "Nom": "Double le résultat d’un dé",
    "Étiquettes": "Gestion de dés",
    "Bonus mouvement parfait": "",
    "Prise": "Pinch",
    "Profil": "Toit",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 7,
    "Nom": "Choisis un dé, sa valeur est 6",
    "Étiquettes": "Gestion de dés",
    "Bonus mouvement parfait": "",
    "Prise": "Flake",
    "Profil": "Vertical",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 8,
    "Nom": "Choisis un dé, sa valeur est 1",
    "Étiquettes": "Gestion de dés",
    "Bonus mouvement parfait": "",
    "Prise": "Crack",
    "Profil": "Vertical",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 12,
    "Nom": "La difficulté de la prochaine prise est 0",
    "Étiquettes": "Déplacement",
    "Bonus mouvement parfait": "",
    "Prise": "Jug",
    "Profil": "Dévers",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 100,
    "Nom": "Nouvelle beta",
    "Étiquettes": "Déplacement",
    "Bonus mouvement parfait": "",
    "Prise": "Jug",
    "Profil": "Dièdre",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 13,
    "Nom": "En cas de réussite, rejoues",
    "Étiquettes": "Combo, Déplacement",
    "Bonus mouvement parfait": "",
    "Prise": "Pocket",
    "Profil": "Dévers",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 101,
    "Nom": "Nouvelle beta",
    "Étiquettes": "Déplacement",
    "Bonus mouvement parfait": "",
    "Prise": "Pocket",
    "Profil": "Dièdre",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 14,
    "Nom": "En cas d’échec, tu ne tombes pas",
    "Étiquettes": "Déplacement",
    "Bonus mouvement parfait": "",
    "Prise": "Crimp",
    "Profil": "Dévers",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 102,
    "Nom": "Nouvelle beta",
    "Étiquettes": "Déplacement",
    "Bonus mouvement parfait": "",
    "Prise": "Crimp",
    "Profil": "Dièdre",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 15,
    "Nom": "Nouvelle beta",
    "Étiquettes": "Déplacement",
    "Bonus mouvement parfait": "",
    "Prise": "Slopper",
    "Profil": "Dévers",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 16,
    "Nom": "En cas de réussite, un autre joueur grimpe également de un",
    "Étiquettes": "Déplacement, Interaction",
    "Bonus mouvement parfait": "",
    "Prise": "Horn",
    "Profil": "Dévers",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 103,
    "Nom": "Nouvelle beta",
    "Étiquettes": "Déplacement",
    "Bonus mouvement parfait": "",
    "Prise": "Horn",
    "Profil": "Dièdre",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 20,
    "Nom": "Tu ne peux pas clipper ce tour ci",
    "Étiquettes": "#pute, Déplacement",
    "Bonus mouvement parfait": "",
    "Prise": "Pinch",
    "Profil": "Dévers",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 104,
    "Nom": "Nouvelle beta",
    "Étiquettes": "Déplacement",
    "Bonus mouvement parfait": "",
    "Prise": "Pinch",
    "Profil": "Dièdre",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 10,
    "Nom": "En cas de réussite, grimpe de 2 prises",
    "Étiquettes": "Déplacement",
    "Bonus mouvement parfait": "",
    "Prise": "Flake",
    "Profil": "Toit",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 22,
    "Nom": "Clippe en cas de double",
    "Étiquettes": "Déplacement",
    "Bonus mouvement parfait": "",
    "Prise": "Flake",
    "Profil": "Dévers",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 11,
    "Nom": "Le prochain clip est gratuit",
    "Étiquettes": "Déplacement",
    "Bonus mouvement parfait": "",
    "Prise": "Crack",
    "Profil": "Toit",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 18,
    "Nom": "Echange une carte avec un joueur",
    "Étiquettes": "Interaction",
    "Bonus mouvement parfait": "",
    "Prise": "Jug",
    "Profil": "Dalle",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 19,
    "Nom": "Vole une carte à un autre joueur",
    "Étiquettes": "#pute, Interaction",
    "Bonus mouvement parfait": "",
    "Prise": "Pocket",
    "Profil": "Dalle",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 21,
    "Nom": "Aucun autre joueur ne peut jouer de carte pendant ce tour",
    "Étiquettes": "Interaction",
    "Bonus mouvement parfait": "",
    "Prise": "Crimp",
    "Profil": "Dalle",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 24,
    "Nom": "Le joueur devant toi tombe à son dernier clip",
    "Étiquettes": "#pute, Interaction",
    "Bonus mouvement parfait": "",
    "Prise": "Slopper",
    "Profil": "Dalle",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 25,
    "Nom": "Le premier grimpeur tombe à son dernier clip",
    "Étiquettes": "#pute, Interaction",
    "Bonus mouvement parfait": "",
    "Prise": "Horn",
    "Profil": "Dalle",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 17,
    "Nom": "Echange ta position avec celle d’un autre joueur",
    "Étiquettes": "#pute, Interaction",
    "Bonus mouvement parfait": "",
    "Prise": "Crack",
    "Profil": "Dévers",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 112,
    "Nom": "Pioche un équipement au hasard",
    "Étiquettes": "Combo",
    "Bonus mouvement parfait": "",
    "Prise": "Crimp",
    "Profil": "Toit",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Equipement"
  },
  {
    "Identifiant": 105,
    "Nom": "Pioche 2 cartes",
    "Étiquettes": "Combo",
    "Bonus mouvement parfait": "",
    "Prise": "Slopper",
    "Profil": "Dièdre",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 26,
    "Nom": "Pioche 2 cartes",
    "Étiquettes": "Combo",
    "Bonus mouvement parfait": "",
    "Prise": "Pinch",
    "Profil": "Dalle",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 27,
    "Nom": "Pioche 1 carte",
    "Étiquettes": "Combo",
    "Bonus mouvement parfait": "",
    "Prise": "Flake",
    "Profil": "Dalle",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 107,
    "Nom": "Pioche 1 carte",
    "Étiquettes": "Combo",
    "Bonus mouvement parfait": "",
    "Prise": "Flake",
    "Profil": "Dièdre",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 108,
    "Nom": "Pioche 1 carte",
    "Étiquettes": "Combo",
    "Bonus mouvement parfait": "",
    "Prise": "Crack",
    "Profil": "Dalle",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 28,
    "Nom": "Garde une carte jouée dans ta main",
    "Étiquettes": "Combo",
    "Bonus mouvement parfait": "",
    "Prise": "Crack",
    "Profil": "Cheminée",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 106,
    "Nom": "Pioche 1 carte",
    "Étiquettes": "Combo",
    "Bonus mouvement parfait": "",
    "Prise": "Crack",
    "Profil": "Dièdre",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 33,
    "Nom": "Lance un dé supplémentaire, si c’est un 1 tu tombes automatiquement",
    "Étiquettes": "Chaos",
    "Bonus mouvement parfait": "",
    "Prise": "Jug",
    "Profil": "Cheminée",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 110,
    "Nom": "Ignore les conditions",
    "Étiquettes": "Chaos",
    "Bonus mouvement parfait": "",
    "Prise": "Pocket",
    "Profil": "Vertical",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Conditions"
  },
  {
    "Identifiant": 34,
    "Nom": "Ajoute +3 au total, mais tu perds tous tes dés même en cas de réussite",
    "Étiquettes": "Chaos",
    "Bonus mouvement parfait": "",
    "Prise": "Pocket",
    "Profil": "Cheminée",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 35,
    "Nom": "Joue un tour supplémentaire si tu tombes",
    "Étiquettes": "Chaos",
    "Bonus mouvement parfait": "",
    "Prise": "Crimp",
    "Profil": "Cheminée",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 111,
    "Nom": "Change les conditions",
    "Étiquettes": "Chaos",
    "Bonus mouvement parfait": "",
    "Prise": "Slopper",
    "Profil": "Dévers",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Conditions"
  },
  {
    "Identifiant": 36,
    "Nom": "Recommence ce tour, la prise a +2 de difficulté",
    "Étiquettes": "Chaos",
    "Bonus mouvement parfait": "",
    "Prise": "Slopper",
    "Profil": "Cheminée",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 37,
    "Nom": "Tu ne peux lancer que 2 dés. Avance de 2 prises, cas de réussite",
    "Étiquettes": "Chaos",
    "Bonus mouvement parfait": "",
    "Prise": "Horn",
    "Profil": "Cheminée",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 38,
    "Nom": "En cas de réussite, un autre joueur descend d’une prise",
    "Étiquettes": "#pute, Chaos",
    "Bonus mouvement parfait": "",
    "Prise": "Pinch",
    "Profil": "Cheminée",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 39,
    "Nom": "Les autres joueurs perdent 1 dé",
    "Étiquettes": "#pute, Chaos",
    "Bonus mouvement parfait": "",
    "Prise": "Flake",
    "Profil": "Cheminée",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 113,
    "Nom": "Vole un équipement à un autre joueur",
    "Étiquettes": "#pute, Interaction",
    "Bonus mouvement parfait": "",
    "Prise": "Flake",
    "Profil": "Dièdre",
    "Type": "Mouvement",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Equipement"
  },
  {
    "Identifiant": 51,
    "Nom": "Jug",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Jug",
    "Profil": "Vertical",
    "Type": "Prise",
    "Clip": 3,
    "Difficulté": 1,
    "Extension": ""
  },
  {
    "Identifiant": 78,
    "Nom": "Jug",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Jug",
    "Profil": "Toit",
    "Type": "Prise",
    "Clip": 5,
    "Difficulté": 3,
    "Extension": ""
  },
  {
    "Identifiant": 53,
    "Nom": "Jug",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Jug",
    "Profil": "Dévers",
    "Type": "Prise",
    "Clip": 2,
    "Difficulté": 3,
    "Extension": ""
  },
  {
    "Identifiant": 76,
    "Nom": "Jug",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Jug",
    "Profil": "Dalle",
    "Type": "Prise",
    "Clip": 4,
    "Difficulté": 1,
    "Extension": ""
  },
  {
    "Identifiant": 77,
    "Nom": "Jug",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Jug",
    "Profil": "Cheminée",
    "Type": "Prise",
    "Clip": 4,
    "Difficulté": 2,
    "Extension": ""
  },
  {
    "Identifiant": 52,
    "Nom": "Jug",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Jug",
    "Profil": "Dièdre",
    "Type": "Prise",
    "Clip": 3,
    "Difficulté": 2,
    "Extension": ""
  },
  {
    "Identifiant": 54,
    "Nom": "Pocket",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Pocket",
    "Profil": "Vertical",
    "Type": "Prise",
    "Clip": 3,
    "Difficulté": 8,
    "Extension": ""
  },
  {
    "Identifiant": 81,
    "Nom": "Pocket",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Pocket",
    "Profil": "Toit",
    "Type": "Prise",
    "Clip": 1,
    "Difficulté": 10,
    "Extension": ""
  },
  {
    "Identifiant": 56,
    "Nom": "Pocket",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Pocket",
    "Profil": "Dévers",
    "Type": "Prise",
    "Clip": 6,
    "Difficulté": 10,
    "Extension": ""
  },
  {
    "Identifiant": 79,
    "Nom": "Pocket",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Pocket",
    "Profil": "Dalle",
    "Type": "Prise",
    "Clip": 4,
    "Difficulté": 8,
    "Extension": ""
  },
  {
    "Identifiant": 55,
    "Nom": "Pocket",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Pocket",
    "Profil": "Cheminée",
    "Type": "Prise",
    "Clip": 5,
    "Difficulté": 9,
    "Extension": ""
  },
  {
    "Identifiant": 80,
    "Nom": "Pocket",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Pocket",
    "Profil": "Dièdre",
    "Type": "Prise",
    "Clip": 2,
    "Difficulté": 9,
    "Extension": ""
  },
  {
    "Identifiant": 84,
    "Nom": "Crimp",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Crimp",
    "Profil": "Vertical",
    "Type": "Prise",
    "Clip": 3,
    "Difficulté": 4,
    "Extension": ""
  },
  {
    "Identifiant": 72,
    "Nom": "Crimp",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Crimp",
    "Profil": "Toit",
    "Type": "Prise",
    "Clip": 2,
    "Difficulté": 6,
    "Extension": ""
  },
  {
    "Identifiant": 82,
    "Nom": "Crimp",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Crimp",
    "Profil": "Dévers",
    "Type": "Prise",
    "Clip": 5,
    "Difficulté": 6,
    "Extension": ""
  },
  {
    "Identifiant": 83,
    "Nom": "Crimp",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Crimp",
    "Profil": "Dalle",
    "Type": "Prise",
    "Clip": 4,
    "Difficulté": 4,
    "Extension": ""
  },
  {
    "Identifiant": 73,
    "Nom": "Crimp",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Crimp",
    "Profil": "Cheminée",
    "Type": "Prise",
    "Clip": 5,
    "Difficulté": 5,
    "Extension": ""
  },
  {
    "Identifiant": 74,
    "Nom": "Crimp",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Crimp",
    "Profil": "Dièdre",
    "Type": "Prise",
    "Clip": 3,
    "Difficulté": 5,
    "Extension": ""
  },
  {
    "Identifiant": 70,
    "Nom": "Slopper",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Slopper",
    "Profil": "Vertical",
    "Type": "Prise",
    "Clip": 3,
    "Difficulté": 5,
    "Extension": ""
  },
  {
    "Identifiant": 69,
    "Nom": "Slopper",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Slopper",
    "Profil": "Toit",
    "Type": "Prise",
    "Clip": 2,
    "Difficulté": 6,
    "Extension": ""
  },
  {
    "Identifiant": 68,
    "Nom": "Slopper",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Slopper",
    "Profil": "Dévers",
    "Type": "Prise",
    "Clip": 6,
    "Difficulté": 7,
    "Extension": ""
  },
  {
    "Identifiant": 85,
    "Nom": "Slopper",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Slopper",
    "Profil": "Dalle",
    "Type": "Prise",
    "Clip": 5,
    "Difficulté": 5,
    "Extension": ""
  },
  {
    "Identifiant": 86,
    "Nom": "Slopper",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Slopper",
    "Profil": "Cheminée",
    "Type": "Prise",
    "Clip": 5,
    "Difficulté": 6,
    "Extension": ""
  },
  {
    "Identifiant": 87,
    "Nom": "Slopper",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Slopper",
    "Profil": "Dièdre",
    "Type": "Prise",
    "Clip": 4,
    "Difficulté": 7,
    "Extension": ""
  },
  {
    "Identifiant": 67,
    "Nom": "Horn",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Horn",
    "Profil": "Vertical",
    "Type": "Prise",
    "Clip": 4,
    "Difficulté": 2,
    "Extension": ""
  },
  {
    "Identifiant": 66,
    "Nom": "Horn",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Horn",
    "Profil": "Toit",
    "Type": "Prise",
    "Clip": 3,
    "Difficulté": 3,
    "Extension": ""
  },
  {
    "Identifiant": 65,
    "Nom": "Horn",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Horn",
    "Profil": "Dévers",
    "Type": "Prise",
    "Clip": 5,
    "Difficulté": 4,
    "Extension": ""
  },
  {
    "Identifiant": 88,
    "Nom": "Horn",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Horn",
    "Profil": "Dalle",
    "Type": "Prise",
    "Clip": 4,
    "Difficulté": 2,
    "Extension": ""
  },
  {
    "Identifiant": 89,
    "Nom": "Horn",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Horn",
    "Profil": "Cheminée",
    "Type": "Prise",
    "Clip": 4,
    "Difficulté": 3,
    "Extension": ""
  },
  {
    "Identifiant": 90,
    "Nom": "Horn",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Horn",
    "Profil": "Dièdre",
    "Type": "Prise",
    "Clip": 2,
    "Difficulté": 4,
    "Extension": ""
  },
  {
    "Identifiant": 64,
    "Nom": "Pinch",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Pinch",
    "Profil": "Vertical",
    "Type": "Prise",
    "Clip": 3,
    "Difficulté": 6,
    "Extension": ""
  },
  {
    "Identifiant": 63,
    "Nom": "Pinch",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Pinch",
    "Profil": "Toit",
    "Type": "Prise",
    "Clip": 2,
    "Difficulté": 7,
    "Extension": ""
  },
  {
    "Identifiant": 62,
    "Nom": "Pinch",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Pinch",
    "Profil": "Dévers",
    "Type": "Prise",
    "Clip": 2,
    "Difficulté": 8,
    "Extension": ""
  },
  {
    "Identifiant": 91,
    "Nom": "Pinch",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Pinch",
    "Profil": "Dalle",
    "Type": "Prise",
    "Clip": 5,
    "Difficulté": 6,
    "Extension": ""
  },
  {
    "Identifiant": 92,
    "Nom": "Pinch",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Pinch",
    "Profil": "Cheminée",
    "Type": "Prise",
    "Clip": 4,
    "Difficulté": 7,
    "Extension": ""
  },
  {
    "Identifiant": 93,
    "Nom": "Pinch",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Pinch",
    "Profil": "Dièdre",
    "Type": "Prise",
    "Clip": 5,
    "Difficulté": 8,
    "Extension": ""
  },
  {
    "Identifiant": 96,
    "Nom": "Flake",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Flake",
    "Profil": "Vertical",
    "Type": "Prise",
    "Clip": 3,
    "Difficulté": 3,
    "Extension": ""
  },
  {
    "Identifiant": 60,
    "Nom": "Flake",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Flake",
    "Profil": "Toit",
    "Type": "Prise",
    "Clip": 6,
    "Difficulté": 5,
    "Extension": ""
  },
  {
    "Identifiant": 59,
    "Nom": "Flake",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Flake",
    "Profil": "Dévers",
    "Type": "Prise",
    "Clip": 3,
    "Difficulté": 5,
    "Extension": ""
  },
  {
    "Identifiant": 61,
    "Nom": "Flake",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Flake",
    "Profil": "Dalle",
    "Type": "Prise",
    "Clip": 4,
    "Difficulté": 3,
    "Extension": ""
  },
  {
    "Identifiant": 95,
    "Nom": "Flake",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Flake",
    "Profil": "Cheminée",
    "Type": "Prise",
    "Clip": 3,
    "Difficulté": 4,
    "Extension": ""
  },
  {
    "Identifiant": 94,
    "Nom": "Flake",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Flake",
    "Profil": "Dièdre",
    "Type": "Prise",
    "Clip": 4,
    "Difficulté": 4,
    "Extension": ""
  },
  {
    "Identifiant": 57,
    "Nom": "Crack",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Crack",
    "Profil": "Vertical",
    "Type": "Prise",
    "Clip": 4,
    "Difficulté": 7,
    "Extension": ""
  },
  {
    "Identifiant": 58,
    "Nom": "Crack",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Crack",
    "Profil": "Toit",
    "Type": "Prise",
    "Clip": 5,
    "Difficulté": 8,
    "Extension": ""
  },
  {
    "Identifiant": 71,
    "Nom": "Crack",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Crack",
    "Profil": "Dévers",
    "Type": "Prise",
    "Clip": 1,
    "Difficulté": 9,
    "Extension": ""
  },
  {
    "Identifiant": 97,
    "Nom": "Crack",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Crack",
    "Profil": "Dalle",
    "Type": "Prise",
    "Clip": 2,
    "Difficulté": 7,
    "Extension": ""
  },
  {
    "Identifiant": 98,
    "Nom": "Crack",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Crack",
    "Profil": "Cheminée",
    "Type": "Prise",
    "Clip": 6,
    "Difficulté": 8,
    "Extension": ""
  },
  {
    "Identifiant": 99,
    "Nom": "Crack",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "Crack",
    "Profil": "Dièdre",
    "Type": "Prise",
    "Clip": 2,
    "Difficulté": 9,
    "Extension": ""
  },
  {
    "Identifiant": 118,
    "Nom": "",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "",
    "Profil": "",
    "Type": "Equipement",
    "Clip": "",
    "Difficulté": "",
    "Extension": ""
  },
  {
    "Identifiant": 117,
    "Nom": "Genouillère",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "",
    "Profil": "",
    "Type": "Equipement",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Equipement"
  },
  {
    "Identifiant": 116,
    "Nom": "Gants",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "",
    "Profil": "",
    "Type": "Equipement",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Equipement"
  },
  {
    "Identifiant": 115,
    "Nom": "Casque",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "",
    "Profil": "",
    "Type": "Equipement",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Equipement"
  },
  {
    "Identifiant": 109,
    "Nom": "Condi moisies",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "",
    "Profil": "",
    "Type": "Conditions",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Conditions"
  },
  {
    "Identifiant": 75,
    "Nom": "Condis parfaites",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "",
    "Profil": "",
    "Type": "Conditions",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Conditions"
  },
  {
    "Identifiant": 49,
    "Nom": "Leggings galaxy",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "",
    "Profil": "",
    "Type": "Equipement",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Equipement"
  },
  {
    "Identifiant": 48,
    "Nom": "Rape à doigts",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "",
    "Profil": "",
    "Type": "Equipement",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Equipement"
  },
  {
    "Identifiant": 47,
    "Nom": "Strap",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "",
    "Profil": "",
    "Type": "Equipement",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Equipement"
  },
  {
    "Identifiant": 46,
    "Nom": "Chaussettes dans chaussons",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "",
    "Profil": "",
    "Type": "Equipement",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Equipement"
  },
  {
    "Identifiant": 45,
    "Nom": "Livre sous knee pad",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "",
    "Profil": "",
    "Type": "Equipement",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Equipement"
  },
  {
    "Identifiant": 44,
    "Nom": "Pieds nus",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "",
    "Profil": "",
    "Type": "Equipement",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Equipement"
  },
  {
    "Identifiant": 43,
    "Nom": "Perche à dégaine",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "",
    "Profil": "",
    "Type": "Equipement",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Equipement"
  },
  {
    "Identifiant": 42,
    "Nom": "Dégaine longue",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "",
    "Profil": "",
    "Type": "Equipement",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Equipement"
  },
  {
    "Identifiant": 41,
    "Nom": "Magnésie",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "",
    "Profil": "",
    "Type": "Equipement",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Equipement"
  },
  {
    "Identifiant": 40,
    "Nom": "Chaussons",
    "Étiquettes": "",
    "Bonus mouvement parfait": "",
    "Prise": "",
    "Profil": "",
    "Type": "Equipement",
    "Clip": "",
    "Difficulté": "",
    "Extension": "Equipement"
  }
];

const printableArea = document.getElementById('printable-area');
const holdTemplate = document.querySelector('#templates .hold');
const movementTemplate = document.querySelector('#templates .movement');

const holdCards = cards.filter(entry => entry.Type === 'Prise');
const movementCards = cards.filter(entry => entry.Type === 'Mouvement');


holdCards.forEach(entry => {
    const clone = holdTemplate.cloneNode(true);

    clone.querySelector('.name').textContent = entry.Nom;
    clone.querySelector('.diff').textContent = entry.Difficulté;
    clone.querySelector('.clip').textContent = entry.Clip;
    clone.setAttribute('data-id', 'hold-' + entry.Nom.toLowerCase());

    printableArea.appendChild(clone);
});
